### ISSUE TITLE
问句返回结果页数过多时，loop比较影响性能。

### ISSUE THREAD

**Issue by xmsley614** [zsrl/pywencai#10]
大部分时间我们可能关注的股票是特定的某几个或者有一个确切的范围，正好问财也有相应的接口，与findDataList类似。可以传入相应参数，将自定义的股票放在结果的最前处返回。这样可以只取第一页或者前几页即可得到自己想要结果。
![image](https://github.com/zsrl/pywencai/assets/73490142/6adc5641-65cc-4d0e-b49f-8b7c9a476405)

如果方便的话，我可以提个PR

**Comment by zsrl** [comment]
@xmsley614 可以，欢迎提pr!

**Comment by zsrl** [comment]
已解决，并发版，更新v0.9.0
