### ISSUE TITLE
'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by rainwindchen** [zsrl/pywencai#15]
原有问财是可以查到数据的

res = pywencai.get(query='浸没式液冷')
print(res)

![1](https://github.com/zsrl/pywencai/assets/140318
![2](https://github.com/zsrl/pywencai/assets/140318701/3f022460-70f8-4df3-b0da-4f8586396049)
701/d61e2ea5-e8fc-4656-99ec-27733f2d9449)

**Comment by zsrl** [comment]
@rainwindchen 需要python3.8+

**Comment by FLYPEGION** [comment]
@rainwindchen   目前妥协的解决办法是 res = pywencai.get(query='浸没式液冷 股票') 可以解决你的问题 我后几天找时间试试看能不能改一下pywencai源码

**Comment by FLYPEGION** [comment]
@rainwindchen @zsrl 这个问题的原因是问财在解析的时候把你的问句解析成了查询信息板块 而不是A股板块 导致返回的网络响应里没有get-robot-data 导致pywencai库无法解析 pywencai库内wencai第180行params为nonetype get报错  至于解析成查询信息板块的原因 我试了一下 可能是因为A股板块当时没有加载出数据 也可能是单纯问财解析成了查询信息板块 这个问题应该和python版本是无关的 我在python3.8版本也碰到了这个问题

**Comment by FLYPEGION** [comment]
这是问财本身的原因。问财在解析的时候把你的问句解析成了查询信息板块。
导致返回的网络响应里没有get-robot-data 导致pywencai库无法解析 pywencai库内wencai第180行params为nonetype get报错。
至于原因，可能是问财对问句解析有问题或者暂时没有符合条件的股票或是数据延迟或是服务器不稳定造成的。
这个问题应该和python版本是无关的 我在python3.8版本也碰到了这个问题。

**Comment by FLYPEGION** [comment]
@rainwindchen 这是问财本身的原因。问财在解析的时候把你的问句解析成了查询信息板块。
导致返回的网络响应里没有get-robot-data 导致pywencai库无法解析 pywencai库内wencai第180行params为nonetype get报错。
至于原因，可能是问财对问句解析有问题或者暂时没有符合条件的股票或是数据延迟或是服务器不稳定造成的。
这个问题应该和python版本是无关的 我在python3.8版本也碰到了这个问题。

**Comment by FLYPEGION** [comment]
@rainwindchen 你在库报错的时候把相同问句输入问财网页 大概率也是不返回股票结果的
使用“大概率”这个词是因为输入网页和输入问句不是同时的 小概率是会返回结果的

**Comment by FLYPEGION** [comment]
@rainwindchen 你在库报错的时候在问财网页搜索相同问句 大概率也是不返回股票结果的
使用“大概率”这个词是因为输入网页和输入问句不是同时的 小概率是会返回结果的

**Comment by zsrl** [comment]
![image](https://github.com/zsrl/pywencai/assets/4284926/51b30abe-a1a9-4d1c-b88f-11420f95fb8a)
@rainwindchen 试了一下你的问句，再问财网页上也搜不到，所以会报错。
