### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by gamma05772** [zsrl/pywencai#16]
File "/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/_Code_/BC/app.py", line 158, in home
    res = pywencai.get(query='退市股票')
  File "/opt/anaconda3/lib/python3.9/site-packages/pywencai/wencai.py", line 180, in get
    data = params.get('data')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by gamma05772** [comment]
headers['hexin-v'] = execjs.compile(open(jsFileName, 'r').read()).call("v")
        
        session = requests.Session()
        session.headers.update(headers)

        url='http://x.10jqka.com.cn/unifiedwap/unified-wap/v2/result/get-robot-data'
        r = session.post(url,data=payload,json=None)#print ('hexin-v:',session.headers['hexin-v'])

        datas = r.json()['data']['answer'][0]['txt'][0]['content']['components'][0]['data']['datas']#print('result:',r.json())
        columns=r.json()['data']['answer'][0]['txt'][0]['content']['components'][0]['data']['columns']#print(columns)

        df=pd.DataFrame().from_dict(datas)

this is my method,but not work today,maybe 同花顺 has changed something.

**Comment by AzenXu** [comment]
same error, ths must do something bad

**Comment by dick318** [comment]
hexin-v 算法改了

**Comment by zsrl** [comment]
已解决，升级v0.11.0
