### ISSUE TITLE
'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by douzi95** [zsrl/pywencai#17]
![wencai](https://github.com/zsrl/pywencai/assets/5927977/18380b98-ffdf-4a81-8e9b-e2117bdd8ff9)

**Comment by zsrl** [comment]
@douzi95 已解决，升级v0.11.0

**Comment by douzi95** [comment]
厉害   大佬

**Comment by douzi95** [comment]
更新后运行还是同样的异常

**Comment by zsrl** [comment]
![93a4559b9fc63e67330434fd30cfd68](https://github.com/zsrl/pywencai/assets/4284926/8f541c6d-2ead-46d0-a544-adc4065f13d9)
看下文档里，有新的环境依赖，安装下再试试

**Comment by zsrl** [comment]
@douzi95

**Comment by whnet** [comment]
'NoneType' object has no attribute 'get',同样的问题，追踪到hexin-v.js没有运行

**Comment by douzi95** [comment]
@zsrl  已经没有问题了
我的是jsdom没装
