### ISSUE TITLE
这个是分页爬取吧？

### ISSUE THREAD

**Issue by conancheng** [zsrl/pywencai#2]
我测试了一下，全部数据需要31秒。。。拿来做盘后分析问题不大 就是实时抓取一些需要的数据太慢了 自从问财封了接口后，短时间一次性获取所有股票的数据不方便了，能解决一下登入账号后获取全部数据的问题吗？
![image](https://user-images.githubusercontent.com/24214834/193168065-3ec96ffd-cca0-4dea-b4f7-d623fcc5e911.png)

**Comment by zsrl** [comment]
是的，因为分页限制，只能循环获取，耗时比较长。

登录后可以解除分页限制吗，是否需要付费账号，这个我还没试过，如果可以，我可以尝试弄一下。

**Comment by zsrl** [comment]
> 你试试，因为之前wencai那个公开库:https://github.com/GraySilver/wencai 不支持账号登陆获取数据，我浏览器登陆后用查询的地址可以一次性获取全部的，但是我看到每次查询的cookies都是在不断变化，我就没辙了，就是普通注册的账号，不是付费的

好的，我研究研究

**Comment by FFFKKK-123** [comment]
请问下，有付费账号，怎么获得付费账号可以获得的一些信息，比如竞价实际换手率，单纯这样跑，是拿不到这个数据

**Comment by zsrl** [comment]
> 请问下，有付费账号，怎么获得付费账号可以获得的一些信息，比如竞价实际换手率，单纯这样跑，是拿不到这个数据

目前未提供登录账号访问的方式，有时间研究下。

**Comment by FFFKKK-123** [comment]
> 

嗯嗯，辛苦

**Comment by zsrl** [comment]
> 你试试，因为之前wencai那个公开库:https://github.com/GraySilver/wencai 不支持账号登陆获取数据，我浏览器登陆后用查询的地址可以一次性获取全部的，但是我看到每次查询的cookies都是在不断变化，我就没辙了，就是普通注册的账号，不是付费的

我尝试了一下，目前能查到的查询接口都设置了最大条数限制，浏览器上也最多只能返回100条，所以没什么解决方法，只能分页了。

**Comment by zsrl** [comment]
> 请问下，有付费账号，怎么获得付费账号可以获得的一些信息，比如竞价实际换手率，单纯这样跑，是拿不到这个数据

付费账号理论请求加上cookie就可以了，但我目前没有付费账号，无法测试，如有需要，可以自己在header里加上cookie试试。或者私下联系我，用你的环境测试下。
