### ISSUE TITLE
最新版本无法获取数据

### ISSUE THREAD

**Issue by 95ge** [zsrl/pywencai#23]
首先，非常感谢你的开源！
我的程序从2023年2月份一直在使用pywencai，但到2023年8月8号左右，无法返回数据。不知道是不是问财加强了反爬措施。

**Comment by zsrl** [comment]
升级最新版，nodejs版本需要v16+

**Comment by 95ge** [comment]
![图片](https://github.com/zsrl/pywencai/assets/92923254/8c0df476-acfe-4c6e-8a9c-205d27f03d52)
我按照您的指导升级了nodejs，似乎还是不行

**Comment by sunshe35** [comment]
你如果配置好了nodejs，然后升级0.12.0版本肯定是没问题的。

**Comment by zsrl** [comment]
检查一下pywencai的版本，应该为0.12.0

**Comment by 95ge** [comment]
> ![图片](https://user-images.githubusercontent.com/92923254/259618486-8c0df476-acfe-4c6e-8a9c-205d27f03d52.png) 我按照您的指导升级了nodejs，似乎还是不行

目前运行成功，重新安装nodejs到16以后就可以，谢谢大家的耐心解答！
