### ISSUE TITLE
无法获取指数数据

### ISSUE THREAD

**Issue by miaomiaoxwz** [zsrl/pywencai#24]
当问题是“主力净额大于0的行业指数”时，调用pywencai的查询结果还是个股，如下图所示：
![image](https://github.com/zsrl/pywencai/assets/95076883/dc9163cc-6212-423f-b92c-bb7bde4d86f8)
而在问财官网上直接提问“主力净额大于0的行业指数”时，就能得到指数的相关数据，如下图所示：
![image](https://github.com/zsrl/pywencai/assets/95076883/c2fc2f82-8db2-463e-9f37-c854fb69d0f3)
两者的查询结果不匹配。请问这个模块是只能查询个股吗？要怎么获取指数的相关数据呢？

**Comment by kalends** [comment]
query_type  这个参数设置了吗？

我升级到0.12.0版本，获取不到数据呢。

**Comment by zsrl** [comment]
```
res = pywencai.get(query='主力净额大于0的行业指数', query_type='zhishu')
```
![image](https://github.com/zsrl/pywencai/assets/4284926/9f7a58d5-61ea-4d15-891b-5492330e5ac1)

使用query_type
