### ISSUE TITLE
调用pywencai直接报错。

### ISSUE THREAD

**Issue by kalends** [zsrl/pywencai#25]
# Rewritten code with error handling and comments
import pywencai

try:
    # Get a list of delisted stocks sorted by delisting date in ascending order
    res = pywencai.get(query='市盈率<35；市净率<1.8；每股收益增长率>0；利润增长率>0；流动比率>1.8；速动比率>1；市值从小到大排序；非ST；非创业；非科创；非北证', sort_order='asc', loop=True, log=True)

    # Print the result
    print(res)

except Exception as e:
    # Handle any exceptions that may occur
    print(f"Error: {e}")

[pywencai] 2023-08-28 22:11:29,417 - INFO - 获取condition开始
[pywencai] 2023-08-28 22:11:29,496 - WARNING - 1次尝试失败
[pywencai] 2023-08-28 22:11:29,497 - WARNING - 2次尝试失败
[pywencai] 2023-08-28 22:11:29,499 - WARNING - 3次尝试失败
[pywencai] 2023-08-28 22:11:29,502 - WARNING - 4次尝试失败
[pywencai] 2023-08-28 22:11:29,505 - WARNING - 5次尝试失败
[pywencai] 2023-08-28 22:11:29,507 - WARNING - 6次尝试失败
[pywencai] 2023-08-28 22:11:29,509 - WARNING - 7次尝试失败
[pywencai] 2023-08-28 22:11:29,513 - WARNING - 8次尝试失败
[pywencai] 2023-08-28 22:11:29,514 - WARNING - 9次尝试失败
[pywencai] 2023-08-28 22:11:29,516 - WARNING - 10次尝试失败
[pywencai] 2023-08-28 22:11:29,516 - INFO - 获取get_robot_data失败
Error: 'NoneType' object has no attribute 'get'

**Comment by zsrl** [comment]
![image](https://github.com/zsrl/pywencai/assets/4284926/5f030aff-2914-458a-b0de-f829a02f0d5f)
未复现，请排查版本，升级最新版后尝试。
