### ISSUE TITLE
问财官方是不是又升级了，无法爬取

### ISSUE THREAD

**Issue by NicholasQu** [zsrl/pywencai#34]
[pywencai] 2023-11-22 16:12:52,412 - INFO - 获取get_robot_data失败
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_10512\1512741554.py in <module>

E:\DevEnvs\svn_hquant\jupyter\Global_Functions.py in h_THS_CacheStockBlock()
   1962     importlib.reload(pywencai)
   1963 
-> 1964     res = pywencai.get(question='已省略;',  sort_key='股票代码', sort_order='asc', \
   1965                       # sleep=1, \
   1966                        loop=True, log=True,)

E:\DevEnvs\github\pywencai\pywencai\wencai.py in get(loop, **kwargs)
    180     kwargs = {replace_key(key): value for key, value in kwargs.items()}
    181     params = get_robot_data(**kwargs)
--> 182     data = params.get('data')
    183     condition = _.get(data, 'condition')
    184     if condition is not None:

AttributeError: 'NoneType' object has no attribute 'get'

**Comment by zsrl** [comment]
大概率是你访问过多被限制

**Comment by NicholasQu** [comment]
用框架访问被限制了，用网页是不被限制的。 这玩意有办法破么？ @zsrl

**Comment by NicholasQu** [comment]
> 大概率是你访问过多被限制

我基本上2-3天访问一次同一个Query，应该不算多的。
