### ISSUE TITLE
pywencai.get()返回的查询结果出问题，无法正确解析为df，需要升级pywencai接口

### ISSUE THREAD

**Issue by gsb7814** [zsrl/pywencai#40]
pywencai.get()返回的查询结果无法解析为df，初步分析应该是2024.1.10日i问财官方页面更新了查询结果展示页面，导致解析查询结果数据出问题。
比如，我调用get()返回的df.columns，报错如下：AttributeError: 'dict' object has no attribute  'columns'.
经过初步分析，返回的数据类型为dict，形如：
<class 'dict'>
{'请填写主题': '<p>为你找到<strong><span style="color:#ff2346">5348</span></strong>只符合条件的A股，具体如下：</p>', 'xuangu_tableV1': .......

据此分析是由于i问财官方页面更新了查询结果展示页面，导致pywencai的get接口解析html结果出错，无法生成df。不妥之处请指正。
感谢大佬们分享的pywencai，期待大佬们的版本更新，谢谢！

**Comment by gsb7814** [comment]
问题已解决，将0.12.0更新到最新1.9日最新的版本0.12.2就ok了，谢谢。

**Comment by xujianjun99** [comment]
作者牛🐮🐮🐮
