### ISSUE TITLE
在用conbond的时候的问题

### ISSUE THREAD

**Issue by bthuntergg** [zsrl/pywencai#42]
出现 返回类型未dict
返回Key: 请填写主题
返回Key: xuangu_tableV1
返回Key: 问财选可转债
返回Key: container

数据框在 xuangu_tableV1里，但仅仅只能显示10个数据

key： 问财选可转债                                          q  ... 股票代码
0  问题内容 ...

container {'btn1':                                          q  ... 股票代码
0 问题内容  ...

**Comment by zsrl** [comment]
看不懂你写的啥，有问题先升级
