### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by xyxy** [zsrl/pywencai#50]
python -V
Python 3.12.3

python test.py 
Traceback (most recent call last):
  File "/root/test.py", line 2, in <module>
    res = pywencai.get(query='退市股票', sort_key='退市@退市日期', sort_order='asc')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pywencai/wencai.py", line 185, in get
    data = params.get('data')
           ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by xyxy** [comment]
> python -V Python 3.12.3
> 
> python test.py Traceback (most recent call last): File "/root/test.py", line 2, in res = pywencai.get(query='退市股票', sort_key='退市@退市日期', sort_order='asc') ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pywencai/wencai.py", line 185, in get data = params.get('data') ^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'get'

**Comment by 2855321556** [comment]
怎么解决的
