### ISSUE TITLE
生成hexin-v的nodejs的版本需要提醒一下

### ISSUE THREAD

**Issue by shenjing023** [zsrl/pywencai#6]
我用nodejs --version=12.x版本的时候生成的hexin-v是错误的，后来升级nodejs为最新版才解决

**Comment by zsrl** [comment]
嗯嗯，用最新版

**Comment by shenjing023** [comment]
今天又试了一下，又不行了，似乎跟nodejs版本无关，请问生成的hexin-v能使用的概率高吗
