### ISSUE TITLE
生成的hexin-v能使用的概率高吗

### ISSUE THREAD

**Issue by shenjing023** [zsrl/pywencai#7]
今天又试了一下，又不行了，似乎跟nodejs版本无关，请问生成的hexin-v能使用的概率高吗

_Originally posted by @shenjing023 in https://github.com/zsrl/pywencai/issues/6#issuecomment-1546798398_

**Comment by zsrl** [comment]
@shenjing023 报错详情可以发一下，我这里没遇到类似的问题

**Comment by shenjing023** [comment]
应该是我wsl2的网络问题

**Comment by zsrl** [comment]
@shenjing023 嗯嗯， 可以进QQ群讨论，随时反馈问题：399207347
