### ISSUE TITLE
使用pywencai后使用logging库全局basicConfig配置不生效

### ISSUE THREAD

**Issue by FLYPEGION** [zsrl/pywencai#8]
问题
在全局中使用logging的basicConfig，与pywencai库冲突，全局样式不生效。
建议
建议在库中使用logger替代basicConfig来避免。

e.g.1:
import logging
import pywencai

logging.basicConfig(level=logging.INFO,
                    filename='work.log')
无法生成work.log

e.g.2:
case1
import logging
logging.basicConfig(level=logging.INFO)
logging.info(1)
 out: [pywencai] 2023-05-15 04:16:22,364 - INFO - 1

case2
import logging
logging.basicConfig(level=logging.INFO)
logging.info(1)
out: INFO:root:1

**Comment by zsrl** [comment]
@FLYPEGION 感谢提交pr，已发布0.8.6版本
